### ISSUE TITLE
docker-compose would be nice

### ISSUE THREAD

**Issue by davidrutland** [TBosak/mkfd#11]
Superb project - and I love it.

However, it would be neat to be able to manage the docker comtainer via docker-compose.

**Comment by bigdale123** [comment]
In the mean time, you can just use [Composerize](https://www.composerize.com/). Here is what it spits out for the current version of mkfd (whatever the version is as of 05/10/2025):

```yaml
name: <your project name>
services:
    mkfd:
        ports:
            - 5000:5000
        volumes:
            - /local/mount/path:/app/configs
        environment:
            - PASSKEY=your_passkey
            - COOKIE_SECRET=your_cookie_secret
            - ENCRYPTION_KEY=your_encryption_key
            - SSL=true/false
        image: tbosk/mkfd:latest
```
