### ISSUE TITLE
Everything beyond tag 22 has stopped working for me

### ISSUE THREAD

**Issue by etuck** [TBosak/mkfd#13]
I see "mkfd exited with code 137" in the terminal.  Let me know if there are logs I can include here. I don't see anything.

Reverting to tag 22 resolves the problem.

I am using this as my docker-compose.yaml:

```
services:
  mkfd:
    image: tbosk/mkfd:latest
    container_name: mkfd
    environment:
      - PASSKEY=[passkey]
      - COOKIE_SECRET=[cookie secret]
    volumes:
      - [docker config folder]/mkfd/:/configs
    ports:
      - 5002:5000
    restart: unless-stopped
networks: {}
```
