### ISSUE TITLE
Cannot start docker

### ISSUE THREAD

**Issue by piotrkustal** [TBosak/mkfd#14]
Image is successfully pulled but app exits automatically with following log:

error: Unexpected reading "/app/index.ts"
Bun v1.2.8 (Linux x64 baseline)

docker-compose looks like this:

```
version: '3'

services:
  mkfd:
    image: tbosk/mkfd:latest
    ports:
      - "5000:5000"
    volumes:
      - /home/piotr/docker/mkfd/configs:/app/configs
    environment:
      - PASSKEY=CUqS98Hbov6bQmPj
      - COOKIE_SECRET=nvebk0lSKnzBuDgw
      - ENCRYPTION_KEY=LuyJM7wfa6W99oEH
```
