### ISSUE TITLE
Formatting Descriptions in feeds

### ISSUE THREAD

**Issue by bigdale123** [TBosak/mkfd#23]
I have noticed that (specifically in drill chained descriptions) if you try scraping the entire body of an article, the parts will just be concatenated together with no formatting. This looks rather ugly when trying to read it, is there a current way to do this in the latest build? Or would it have to be implemented? I have included an example below.

The way an item description looks now:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.Proin sem ligula, malesuada id turpis quis, cursus vulputate lectus.Praesent bibendum porta felis non condimentum.Donec lacinia fermentum dui sit amet vestibulum.Ut mauris erat, finibus in tortor sit amet, fringilla porta justo. Phasellus convallis neque sed porttitor condimentum.Proin convallis nisl ut auctor placerat. Aliquam erat volutpat.Nunc rutrum tellus ut imperdiet cursus. Curabitur ut libero neque. 
```

The way that would read nicer, with 2 newlines between each element scraped (and closely matches the formatting on the website being scraped):
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin sem ligula, malesuada id turpis quis, cursus vulputate lectus. Praesent bibendum porta felis non condimentum. Donec lacinia fermentum dui sit amet vestibulum.

Ut mauris erat, finibus in tortor sit amet, fringilla porta justo. Phasellus convallis neque sed porttitor condimentum.

Proin convallis nisl ut auctor placerat. Aliquam erat volutpat. Nunc rutrum tellus ut imperdiet cursus. Curabitur ut libero neque. 
```

**Comment by TBosak** [comment]
Do you have a yaml config for a specific case that you could provide? I can take a look later.

**Comment by bigdale123** [comment]
Here's my config for scraping a feed from my local news station, mkfd does a great job, minus pulling in the whole article in a readable format. 

```yml
feedId: 621b4442-b3ef-4cf1-b869-e2632ed5520a
feedName: WBRC Fox 6 News
feedType: webScraping
config:
  title: WBRC Fox 6 News
  baseUrl: https://www.wbrc.com/news/
  method: GET
  route: ''
  params: {}
  headers: {}
  cookieString: ''
  body: {}
  advanced: false
article:
  iterator:
    selector: '*.card-body'
  title:
    selector: h4
    attribute: ''
    stripHtml: false
    rootUrl: ''
    relativeLink: false
    titleCase: false
    iterator: ''
    dateFormat: ''
    drillChain: []
  description:
    selector: ''
    attribute: ''
    stripHtml: false
    rootUrl: ''
    relativeLink: false
    titleCase: false
    iterator: ''
    dateFormat: ''
    drillChain:
      - selector: a
        attribute: href
        isRelative: true
        baseUrl: https://www.wbrc.com
      - selector: article
        attribute: ''
        isRelative: false
        baseUrl: ''
  link:
    selector: a
    attribute: href
    stripHtml: false
    rootUrl: https://www.wbrc.com
    relativeLink: true
    titleCase: false
    iterator: ''
    dateFormat: ''
    drillChain: []
  enclosure:
    selector: ''
    attribute: ''
    stripHtml: false
    rootUrl: ''
    relativeLink: false
    titleCase: false
    iterator: ''
    dateFormat: ''
    drillChain:
      - selector: a
        attribute: href
        isRelative: true
        baseUrl: https://www.wbrc.com
      - selector: figure.media-item
        attribute: ''
        isRelative: false
        baseUrl: https://www.wbrc.com
  date:
    selector: ''
    attribute: ''
    stripHtml: false
    rootUrl: ''
    relativeLink: false
    titleCase: false
    iterator: ''
    dateFormat: ''
    drillChain:
      - selector: a
        attribute: href
        isRelative: true
        baseUrl: https://www.wbrc.com
      - selector: meta[property="article:modified_time"]
        attribute: ''
        isRelative: false
        baseUrl: ''
apiMapping: {}
refreshTime: 5
reverse: false
strict: false
```

Here is an example feed item scraped with that config:
```xml
<item>
<title>
Birmingham Police: 2 shot in Smithfield neighborhood Sunday morning
</title>
<description>
Birmingham Police: 2 shot in Smithfield neighborhood Sunday morningBirmingham Police: 2 shot in Smithfield neighborhood Sunday morning(WBRC)By WBRC Digital StaffPublished: May 11, 2025 at 3:11 PM CDT|Updated: 15 minutes agoEmail This LinkShare on FacebookShare on X (formerly Twitter)Share on PinterestShare on LinkedInBIRMINGHAM, Ala. (WBRC) - Two people were shot in Birmingham Sunday morning, according to Birmingham Police.According to authorities, two people were shot at 9th Street N and 4th Avenue North at 9:48 Sunday morning.Police say the victims suffered non-life threatening injuries.At this time, there is no one in custody.We will update this story as more information becomes available. Get news alerts in the Apple App Store and Google Play Store or subscribe to our email newsletter here.Copyright 2025 WBRC. All rights reserved.
</description>
<link>
https://www.wbrc.com/2025/05/11/birmingham-police-2-shot-smithfield-neighborhood-sunday-morning/
</link>
<guid isPermaLink="false">3464248684658415939</guid>
<dc:creator>mkfd</dc:creator>
<enclosure url="Birmingham Police: 2 shot in Smithfield neighborhood Sunday morning(WBRC)" length="0" type="application/octet-stream"/>
</item>
```
I'm just asking if there is a way to make the description formatted nicer using mkfd.

**Comment by TBosak** [comment]
Got it - I will work on this when I get some free time next.

**Comment by TBosak** [comment]
Also, are you using the latest version? I worked on some url validation for enclosures to try to ensure it grabs urls specifically.

**Comment by bigdale123** [comment]
yep, pulled the docker image yesterday. Here is my compose file, just in case:

```yml
services:
  mkfd:
    ports:
      - 5000:5000
    volumes:
      - /home/dylan/mkfd_configs:/app/configs
    environment:
      - PASSKEY=**********
      - COOKIE_SECRET=**********
      - ENCRYPTION_KEY=**********
      - SSL=false
    image: tbosk/mkfd:latest
```
